urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from world.views import WorldViews
from django_couchdb_utils.openid_consumer.registration import RegistrationConsumer

urlpatterns = patterns('',
)

dev = getattr(settings, 'PROD', None)
if not dev:
    import os
    dirp = os.path.dirname(__file__)
    urlpatterns += patterns('',
        (r'^site_media/(?P<path>.*)$', 'django.views.static.serve', {'document_root':  os.path.join(dirp,'site_media')}),
)

urlpatterns += patterns('',
    (r'^openid/(.*)', RegistrationConsumer()),
    (r'^(.*)', WorldViews()),
)

world/forms.py
from django import forms
from datetime import date
from django.utils.datastructures import SortedDict

BATCH_CHOICES = [(ii, ii) for ii in xrange(1979, date.today().year)]
CLASS_CHOICES = [(ii, ii) for ii in xrange(1, 13)]
EXCLUDE_LIST = ['id', '_id', '_rev', 'csrfmiddlewaretoken', 'doc_type', 
                'registered_on', 'last_edited']

class PersonForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(PersonForm, self).__init__(*args, **kwargs)
        for (name, value) in self.data.items():
            if not name in EXCLUDE_LIST and not name in self.base_fields:
                self.fields[name.decode('utf8')] = forms.CharField()

    user_id   = forms.CharField(widget=forms.HiddenInput, required=False)
    full_name = forms.CharField(widget=forms.HiddenInput, required=False)
    email     = forms.EmailField(widget=forms.TextInput(attrs={"readonly": True, 
                                                               "disabled": True}))

    batch  = forms.CharField(widget=forms.Select(choices=BATCH_CHOICES), help_text="Year passed out / Year expected to pass")
    Class  = forms.CharField(widget=forms.Select(choices=CLASS_CHOICES), help_text="Class passed out")

    bio       = forms.CharField(widget=forms.Textarea, required=False, help_text="To help jog our memories about you!")
    photo     = forms.ImageField(required=False, help_text="How much have you changed since school? ;-)")

    # Location stuff - all location fields are required
    country   = forms.CharField(widget=forms.HiddenInput,  required=False)
    latitude  = forms.FloatField(widget=forms.HiddenInput, required=False)
    longitude = forms.FloatField(widget=forms.HiddenInput, required=False)
    location_description = forms.CharField(widget=forms.HiddenInput, required=False)

    # Contact details
    communication_address = forms.CharField(widget=forms.Textarea, required=False)
    phone = forms.CharField(max_length=10, required=False)
    blog_url = forms.URLField(label="Blog URL", required=False)

    # Education details
    qualification = forms.CharField(max_length=50)
    institution = forms.CharField(max_length=50, required=False)

    # Job details
    occupation = forms.CharField(max_length=50)
    company = forms.CharField(max_length=50, required=False)

    # Instant messaging
    gtalk = forms.CharField(label="GTalk", required=False)
    yahoo = forms.CharField(label="Y! Messenger", required=False)

    # Other profiles
    linkedin = forms.URLField(label="LinkedIn", required=False)
    facebook = forms.URLField(required=False)
    twitter = forms.URLField(required=False)

    def clean(self):
        for (name, value) in self.cleaned_data.items():
            if not value:
                self.cleaned_data.pop(name)
        return self.cleaned_data

PersonSortedDict = SortedDict(PersonForm().fields.items())

templates/person/about.html
{% extends "site_base.html" %}

{% block nav_li_class_home %} class="current"{% endblock %}>

{% block js %}
{% endblock %}

{% block map %}
    <div class="mapContainer major">
        <div id="gmap">&nbsp;</div>
    </div>
{% endblock %}

{% block content %}
{% endblock %}

templates/person/do_list.html
{% extends "site_base.html" %}

{% load switchcase %}

{% block js %}
<script type="text/javascript" src="{{ MEDIA_URL }}js/countryMapping.js"></script>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/map_init.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/do_list.js"></script>
<script type="text/javascript">
  $(document).ready(function() {
    doList("{{ MEDIA_URL }}", "{{ searchkey }}");
  });
</script>
{% endblock %}

{% block map %}
<div class="mapBox" id="map_canvas"></div>
<p style="float: right;">
  {% if user_data.has_previous %}
    <a href="?page={{ user_data.previous_page_number }}">Previous</a>
  {% endif %}
  Viewing page {{ user_data.number }} of {{ user_data.paginator.num_pages }}
  {% if user_data.has_next %}
    <a href="?page={{ user_data.next_page_number }}">Next</a>
  {% endif %}
</p>
{% endblock %}

{% block content %}
<h4>Viewing {{ searchkey }}:<span class="country">{{ searchval }}</span> list</h4>
<p>
  Filter in current page by
  <select id="selectFilter">
  </select>
  <input type="text" id="filterInput" />
  <input type="submit" value="Filter" onclick="filter();" />
</p>
<div id="main">
  {% for row in user_data.object_list %} 
  <span class="neat">
    {% for key,val in row.items %}
      {% switch key %}
        {% case "user_id" %}
          <a class="user_id" href="/user/{{ val }}/">{{ val }}</a>{% ifequal val request.user.username %}(You){% endifequal %}
        {% endcase %}
	{% case "country" %}
	  <a class="country" href="/country/{{ val }}/">
	    <img src="{{ MEDIA_URL }}images/flags/{{ val|lower }}.gif" />
	  </a>
	{% endcase %}
        {% case "full_name" %}
	  <br />
          <span class="full_name">{{ val }}</span><br />
	{% endcase %}
        {% case "course" %}
          <a class="course" href="/course/{{ val }}/">{{ val }}</a><br />
	{% endcase %}
        {% case "batch" %}
          <a class="batch" href="/batch/{{ val }}/">{{ val }}</a><br />
	{% endcase %}
        {% case "location_description" %}
          <span class="location">{{ val }}</span><br />
	{% endcase %}
        {% case "latitude" %}
          <span class="latitude">{{ val }}</span>
	{% endcase %}
        {% case "longitude" %}
          <span class="longitude">{{ val }}</span>
	{% endcase %}
      {% endswitch %}
    {% endfor %}
  </span>
  {% endfor %}
</div>
{% endblock %}

{% block footer %}
<p style="float: right;">
  {% if user_data.has_previous %}
    <a href="?page={{ user_data.previous_page_number }}">Previous</a>
  {% endif %}
  Viewing page {{ user_data.number }} of {{ user_data.paginator.num_pages }}
  {% if user_data.has_next %}
    <a href="?page={{ user_data.next_page_number }}">Next</a>
  {% endif %}
  {{ block.super }}
</p>
{% endblock %}

templates/person/edit_profile.html
{% extends "site_base.html" %}

{% load get_services %}
{% load i18n %}

{% block js %}
<script type="text/javascript" src="{{ MEDIA_URL }}js/addServices.js"></script>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/map_init.js"></script>
<script type="text/javascript">
  $(document).ready(function () { initialize(); });
</script>
{% endblock %}

{% block map %}
<h3 class="message">{{ message }}</h3>
<h3 class="note">Drag the marker to your location.</h3>
<div id="map_canvas" class="mapBox"></div>
{% endblock %}

{% block content %}
<form id="editProfile" action="" method="post" enctype="multipart/form-data">{% csrf_token %}
{{ form.non_field_errors }}
<table id="profile">
{% for field in form %}
  {% if field.is_hidden %}
    {{ field }}
  {% else %}
  {% if field.errors %}
    <tr>
      <td colspan="2">{{ field.errors }}</td>
    </tr>
  {% endif %}
    <tr>
      <th>
	<p>{% with field.name as service %}{% get_service_img service %}{% endwith %}{{ field.label }} {% if field.field.required %}*{% endif %}</p>
	{% if field.help_text %}<p class="help_text">{{ field.help_text }}</p>{% endif %}
      </th>
      <td>{{ field }}</td>
      {% ifequal field.name "photo" %}
        {% if photo %}
          <th>Current profile pic:</th><td><a href="{{ MEDIA_URL }}{{ form.data.photo }}"><img src="{{ MEDIA_URL }}{{ form.data.photo }}" width="150" height="150" /></a></td>
	{% endif %}
      {% endifequal %}
    </tr>
  {% endif %}
{% endfor %}
</table>
<a href="#footer" onclick="addOneMoreService();">{% trans "Add one more field" %}...</a><br />
<input type="submit" value="{% trans "Save" %}" />
</form>
{% endblock %}

templates/person/index.html
{% extends "site_base.html" %}
{% load i18n %}

{% block extra_head %}
<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.13/themes/cupertino/jquery-ui.css" type="text/css" media="all" />
{% endblock %}

{% block js %}
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/map_init.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/nearest.js"></script>
<script type="text/javascript">
  $(document).ready(function(){ 
    nearest("{{ request.user.id }}", "{{ MEDIA_URL }}"); 
    var latlng = new google.maps.LatLng(0, 0);
    map_initialize(1, latlng);
  });
</script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/jquery-ui.min.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/countryMapping.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/indexPage.js"></script>
<script type="text/javascript">
  $(document).ready(function() {
    {% for reg in recent_regs %}
    map_plot({{ reg.latitude }}, {{ reg.longitude }});
    {% endfor %}
 });
</script>
{% endblock %}

{% block content %}
{% if total_people %}
<h3>{% trans "Total number of persons registered" %}: {{ total_people }}</h3>
{% endif %}
<div class="span-6">
  <div id="stat">
    <h4><a href="#">{% trans "Countries" %}</a></h4>
    <div>
      {% for country in countries %}
      <div class="country">
    	<img src="{{ MEDIA_URL }}images/flags/{{ country.key|lower }}.gif" alt="{{ country.key }}" />
    	<p id="{{ country.key }}"></p>
    	<p> : {{ country.value }} </p>
      </div>
    {% endfor %}
    </div>
    <h4><a href="#">{% trans "Batches" %}</a></h4>
    <div>
      {% for batch in batches %}
      <div class="batch">
      	<p id="{{ batch.key }}"><a href="/batch/{{ batch.key }}/">{{ batch.key }}</a></p>
      	<p> : {{ batch.value }}</p>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
<div class="span-18 last">
  <div class="mapBoxIndex" id="map_canvas">&nbsp;</div>
</div>
{% endblock %}

templates/person/nearest.html
{% extends "site_base.html" %}
{% load i18n %}

{% block js %}
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/map_init.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/nearest.js"></script>
<script type="text/javascript">
  $(document).ready(function(){ 
    nearest("{{ request.user.id }}", "{{ MEDIA_URL }}"); 
    var latlng = new google.maps.LatLng(19.97335, -15.8203);
    map_initialize(2, latlng);
  });
</script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/jquery-ui.min.js"></script>
<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.13/themes/cupertino/jquery-ui.css" type="text/css" media="all" />
<script type="text/javascript" src="{{ MEDIA_URL }}js/countryMapping.js"></script>
{% endblock %}

{% block map %}
{% if total_people %}
<h3>{% trans "Total number of persons registered" %}: {{ total_people }}</h3>
{% endif %}
<div>
{% if country %}
 <p>Showing people near to you from country: {{ country }}</p>
{% endif %}

{% if latitude %}
  <p>Showing people near to you from latitude: {{ latitude|stringformat:".4f" }}</p>
{% endif %}

{% if longitude %}
  <p>Showing people near to you from longitude: {{ longitude|stringformat:".4f" }}</p>
{% endif %}
</div>
<div class="mapBox" id="map_canvas">&nbsp;</div>
{% endblock %}

{% block content %}
</div>
<div id="main">
</div>
{% endblock %}

templates/person/search.html
{% extends "site_base.html" %}

{% block js %}
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/jquery-ui.min.js"></script>
<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/cupertino/jquery-ui.css" type="text/css" />    
<script type="text/javascript" src="{{ MEDIA_URL }}js/countryMapping.js"></script>
<script type="text/javascript">
      $(document).ready(function () { 
        var tabs = $("#search").tabs();
        $($("#search a")[0]).click();
      });
      var startBatch = 1979;
      var endBatch = (new Date()).getFullYear();
</script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/search.js"></script>
{% endblock %}

{% block content %}
<h3>Search by</h3>
<div id="search">
  <ul>
    <li><a class="largeText" href="#batch" onclick="setupBatchSearch();">Batch</a></li>
    <!-- <li><a class="largeText" href="#course" onclick="setupCourseSearch();">Course</a></li> -->
    <!-- <li><a class="largeText" href="#class" onclick="setupClassSearch();">Class</a></li> -->
    <li><a class="largeText" href="#country" onclick="setupCountrySearch();">Country</a></li>
  </ul>
    <div id="batch"></div>
    <!-- <div id="course"></div> -->
    <div id="class"></div>
    <div id="country"></div>
</div>
{% endblock %}

templates/person/user_profile.html
{% extends "site_base.html" %}

{% load get_services %}

{% block js %}
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/map_init.js"></script>
<script type="text/javascript">
  $(document).ready(function () {
    initialize();
  });
</script>
{% endblock %}

{% block map %}
<h4>Viewing profile of <span id="fullName">{{ user_data.full_name }}</span></h4>
<a href="/country/{{ user_data.country }}/"><img class="flag" src="{{ MEDIA_URL }}images/flags/{{ user_data.country|lower }}.gif" /></a>
<div id="map_canvas" class="mapBox"></div>
{% endblock %}

{% block content %}
{% if user_data.photo %}<a href="{{ MEDIA_URL }}{{ user_data.photo }}"><img src="{{ MEDIA_URL }}{{ user_data.photo }}" width="150" /></a>{% endif %}
<table id="profile">
  <input id="id_latitude"  type="hidden" value="{{ user_data.latitude }}" />
  <input id="id_longitude" type="hidden" value="{{ user_data.longitude }}" />
  <input id="id_location"  type="hidden" value="{{ user_data.location }}" />
  {% for key,val in user_data.items %}
    <tr><th>{{ key|labelize|title }}</th><td>{% get_service_img key %}{{ val|urlize }}</td></tr>
  {% endfor %}
</table>
{% endblock %}